Providers index api
platanus/2021-1-Grupo4-Movil pull request #15
Opened 2021-05-31 18:59 UTC by fthurtado

Se hizo el index de proveedores, tanto los estilos como la conexión con backend.
Se creo el archivo `api/Providers.js` para manejo de todos los endpoints, además el archivo `navigators/bottomNavigation.js` para el manejo de la navegación y por último una carpeta de `Providers` en screen y styles, para cada uno de los componentes para completar el crud.

# QA

- Ingresar a la app, debería aparecer la opción de proveedores en la barra inferior de navegación.
- Al apretar esa opción se cargan todos los proveedores que existen, aparece un botón de ( + ) el cual no está funcional. Además al apretar cada proveedor específico no pasa nada.

# Por implementar

- Manejo de errores al llamar a la api getProviders
- Desarrollar resto de crud, a partir de esta base

2021-05-31 22:48 UTC, jmsilvas requested changes
Todo perfecttt! Encontré un detalle chico que hay que cambiar en la api (cambiaron el formato del ruteo), pero sería. Dejé una idea pa hacer los styles de los headers igual pa que la pensemos.

2021-05-31 22:48 UTC, jmsilvas commented on config.js
> +      specific: '/api/v1/providers/',
Al parecer cambiaron el formato y hay que usar ${API_VERSION}  en vez de /api/v1. Me acabo de dar cuenta.

2021-05-31 22:48 UTC, jmsilvas commented on styles/Headers/indexProviderStyles.js
> +export default styles;
Hay que ver más adelante si usamos esto, quizás sea buena opción importarlo en los navigators para setearselo a todos de una. Y los que tengan botones los modificamos en la componente misma con el setOptions..

2021-05-31 22:48 UTC, jmsilvas commented on config.js
> +      specific: '/api/v1/providers/',
```suggestion
      index: `${API_VERSION}/providers`,
      specific: `${API_VERSION}/providers/`,
```

2021-06-01 18:57 UTC, smargozzini approved these changes

2021-06-01 19:15 UTC, fthurtado commented on config.js
> +      specific: '/api/v1/providers/',
Toda la razón, que pasta jajaja si yo hice el cambio, good

2021-06-01 19:16 UTC, fthurtado commented on styles/Headers/indexProviderStyles.js
> +export default styles;
Me parece bien 👍

2021-06-01 20:14 UTC, jmsilvas approved these changes

2021-06-01 20:39 UTC, merged