Fix ingredient form
platanus/2021-1-Grupo4-Movil pull request #29
Opened 2021-06-11 01:56 UTC by lldavico

### Contexto

La aplicación lanzaba una excepción al editar el precio de un ingrediente ya creado. Además, no emitia ningún mensaje de alerta al tratar de agregar un ingrediente con valores inválidos, por lo que no ocurría nada.

### Qué hice

* Formatié los valores de precio de ingrediente, forzándolos a ser un entero (el valor a editar llegaba como string)
* Lógica para alertar si un ingrediente tiene un valor inválido, indicando modificar el campo erróneo en el form de ingredientes
* Mini refactor de las condiciones a cumplir para crear un ingrediente correctamente

### QA

* Loguearse a la app
* Crear un ingrediente e ir probando con valores inválidos (en blanco o negativos según el caso)
* Editar el precio de un ingrediente ya creado

Sorry por no adjuntar imágenes, pero es mas un fix/bug que una funcionalidad!!

2021-06-11 03:23 UTC, MariaJosefinaAlliende requested changes
Super! Te dejé 2 mini comentarios

2021-06-11 03:23 UTC, pepina-dev commented on screens/Ingredients/FormIngredientScreen.js
> +    console.log(body)
Se te pasó este log :)

2021-06-11 03:23 UTC, MariaJosefinaAlliende commented on screens/Ingredients/FormIngredientScreen.js
> +  function checkValidValues() {
Cero que quedaría más limpio sin tantos else if, se me ocurre algo mas o menos así: 
```js
function checkValidValues() {
  const validations =  [
    { error: !name.length, message: "Debes asignar un nombre al ingrediente" },
    { error: price <= 0, message: "Debes ingresar un precio válido" },
    { error: quantity <= 0, message: "Debes ingresar una cantidad válida" },
    { error:  !measure.length, message: "Debes asignar un nombre al ingrediente" },
  ];
  const error = validations.find((validation) => (validation.error))
  if ( error ) alert(error.message);
 
  return !!error;
}
```

2021-06-11 03:27 UTC, MariaJosefinaAlliende commented on screens/Ingredients/FormIngredientScreen.js
> -    console.log(body)
Ahí caché que la borraste. Te recomiendo para la próxima  hacer un git rebase con el arreglo en vez de arreglarlo en un commit distinto. Básicamente haces un `git add`  del arreglo al commit, después `git comit --fixup=hash-del-commit-que-quieres-arreglar` y de ahí  `git rebase -i --autosquash hash-del-commit-justo-antes-del-que-quieres-arreglar`. Si el commit que arreglaste ya está pusheado, haces después un `git push --force-with-lease origin nombre-de-tu-branch`. En este post Raimundo lo explica mucho mejor : https://blog.platan.us/manteniendo-la-historia-limpia-usando-git-rebase-5cceecd5367a?gi=7764c727a95c

2021-06-11 14:52 UTC, lldavico reviewed
Gracias por los comentarios!! tomaré en cuenta la sugerencia del gitflow para la proxima. Uno nunca termina de aprender todo lo que se puede hacer jajaja

2021-06-11 14:52 UTC, lldavico commented on screens/Ingredients/FormIngredientScreen.js
> +  function checkValidValues() {
Hola! gracias por la recomendación, no se me habría ocurrido hacerlo así, ya está corregido!

2021-06-11 16:16 UTC, jmsilvas requested changes
Está buenísimo el cambio!!!, Quedó más ordenado el código además. Pillé 2 cosas eso si: se está cayendo el yarn start porque faltó una llave en una función, ahí te lo sugerí. Y lo otro, probé crear ingrediente y no me funcionó, no estoy seguro de que sea culpa de este pr la verdad...

2021-06-11 16:16 UTC, jmsilvas commented on screens/Ingredients/FormIngredientScreen.js
> +    return true;
```suggestion
    return true;}
```

2021-06-11 16:16 UTC, jmsilvas commented on screens/Ingredients/FormIngredientScreen.js
> +    return true;
se está cayendo el yarn start por esto!!! jajaja

2021-06-11 22:03 UTC, jmsilvas approved these changes
Todo ok ahora!

2021-06-14 13:05 UTC, MariaJosefinaAlliende approved these changes
✅  Suuper!

2021-06-14 13:16 UTC, merged