Final version
platanus/2021-1-Grupo4-Movil pull request #37
Opened 2021-06-13 05:03 UTC by nicoparraguez

**Que se hizo**
- estandarizo interfaz con respecto a otros cruds
- Navegación tiene colores y estilo de otros cruds
- Bugs de problemas de la semántica de lenguaje.

**Como se ve**

![WhatsApp Image 2021-06-13 at 01 02 28](https://user-images.githubusercontent.com/30676212/121795943-2abd5d00-cbe3-11eb-91ea-37a618522b10.jpeg)
![WhatsApp Image 2021-06-13 at 01 02 27](https://user-images.githubusercontent.com/30676212/121795944-2b55f380-cbe3-11eb-93b2-0d5e83a0d9cb.jpeg)

2021-06-13 13:13 UTC, AndresGarciadelaHuerta approved these changes
Se ve bien 👏  dejo un detalle de un typo chico nomás

2021-06-13 13:13 UTC, AndresGarciadelaHuerta commented on components/menuRow.js
> +            {`${menu.attributes.portions} ${(menu.attributes.portions === 1 ? 'porcion' : 'porciones')}`}
typo en el singular, es con tilde, `porción`

2021-06-14 00:19 UTC, jmsilvas requested changes
Buena Nico!!! Quedó impeka todo, la probé y todo perfect. Eso si te voy a pedir un favor chico, que me fijé en un detalle que no había cachado antes. Podí cambiar el fondo de los index de menú y receta a kitchengramWhite? Se me pasó en el de recetas y si mirai el de ingredientes es blanco y estos 2 están grises!

2021-06-14 01:12 UTC, nicoparraguez commented on components/menuRow.js
> +            {`${menu.attributes.portions} ${(menu.attributes.portions === 1 ? 'porcion' : 'porciones')}`}
Arreglado en nuevo commit

2021-06-14 02:46 UTC, jmsilvas approved these changes

2021-06-14 12:40 UTC, merged