Keyboard avoid
platanus/2021-1-Grupo4-Movil pull request #39
Opened 2021-06-13 23:55 UTC by jmsilvas

Que se hizo:
- se actualizo vistas de proveedores y el estilo del stack de navegación
- se agregó la funcionalidad de keyboard avoid para que al escribir en inputs estos no queden tapados.
- se corrgieron algunos estilos relacionados a esas vistas para su correcto funcionamiento
- se unificó los mensajes en los index en caso de no haber elementos ('Aún no tienes <elemento>") 

QA:
- ingresar a cada uno de los forms y ver que no quede oculto ninguno de los inputs al intentar escribir
- Para verificar mensajes de "aun no tienes X" crear un usuario nuevo y ver que coincida el mensaje en cada uno de los index
- ver que vistas de proveedores no tengan errores (no debería haber mucho problema porque son iguales a las de ingredientes)

2021-06-14 16:02 UTC, fthurtado commented
# Prueba QA Android

- Form de proveedores:
  - Llenando último input (mínimo de compra) el teclado lo tapa, no se ve lo que se está escribiendo
  - Al editar cambiando el mínimo de compra se cae la app (me parece que por la función formatNumber, se le debe estar pasando un string quizás) [Mismo error en el form de ingredientes, también solo editando el precio, se llama a la misma función]
  - Todo lo demás Gucci 👌 

Y ojo con los conflicts 👀

2021-06-14 16:22 UTC, fthurtado requested changes

2021-06-14 16:22 UTC, fthurtado commented on screens/Ingredients/FormIngredientScreen.js
> +                    ]}
Quizás el cambio de las unidades de ingredientes ya se hizo, habría que revisar! Y hacer rebase con master, para evitar problemas

2021-06-14 16:22 UTC, fthurtado commented on screens/Ingredients/IndexIngredientScreen.js
> +    <Text style={{ color: colors.kitchengramGray600, textAlign: 'center', paddingTop: 15, fontSize: 16 }}>
Por qué estos estilo no se definieron en el archivo de styles de esta screen?

2021-06-14 16:22 UTC, fthurtado commented on screens/Menus/MenusScreen.js
> +    <Text style={{ color: colors.kitchengramGray600, textAlign: 'center', paddingTop: 15, fontSize: 16 }}>
Lo mismo acá

2021-06-14 16:22 UTC, fthurtado commented on screens/Menus/MenusScreen.js
>    return (mounted) && (
Quizás sea bueno implementar esto en los ingredientes (y demás screens), ya que con el state `mounted` se evita mostrar el mensaje de _Aún no tienes menús_ mientras se carga el llamado a la api.
De esta forma, en caso de estar cargándose se podría llamar algún tipo de loading.

2021-06-14 23:16 UTC, jgmontoya approved these changes
Buena, se ve bien! Te dejo un par de comentarios pero son cosas bien menores

2021-06-14 23:16 UTC, jgmontoya commented on screens/Ingredients/FormIngredientScreen.js
> +    <>
Cool, no cachaba [esto](https://reactjs.org/docs/fragments.html#short-syntax)

2021-06-14 23:16 UTC, jgmontoya commented on screens/Ingredients/FormIngredientScreen.js
> +              </Text>
Quedó rara la indentación de este texto (y los otros de este archivo)

2021-06-14 23:16 UTC, jgmontoya commented on screens/Providers/FormProviderScreen.js
> +            </Text>
Acá igual faltó indentar los textos

2021-06-14 23:16 UTC, jgmontoya commented on styles/Ingredients/indexStyles.js
> +    fontSize: 16 },
mejor cerrar la llave en la linea de abajo para ser consistentes

2021-06-14 23:16 UTC, jgmontoya commented on styles/Menus/indexStyles.js
> +    fontSize: 16 },
lo mismo acá

2021-06-14 23:16 UTC, jgmontoya commented on styles/Providers/indexStyles.js
> +    fontSize: 16 },
y acá

2021-06-14 23:16 UTC, jgmontoya commented on styles/Recipes/index.js
> +    fontSize: 16 },
y acá

2021-06-14 23:43 UTC, jmsilvas commented on screens/Ingredients/FormIngredientScreen.js
> +              </Text>
toda la razón, resollvi los conflictos acá arriba y no pasé eso por el linter!

2021-06-14 23:44 UTC, jmsilvas commented on styles/Providers/indexStyles.js
> +    fontSize: 16 },
copy paste jugó chueco jajaja vale

2021-06-22 14:30 UTC, fthurtado approved these changes

2021-06-22 14:45 UTC, merged