Add sign up
platanus/2021-1-Grupo4-Movil pull request #4
Opened 2021-05-04 19:03 UTC by jmsilvas

Que se hizo:
- refactor de api según propuesto en pr (ver carpeta api)
- cambio de idioma app a español 
- conexión de sign up a api
- muestra de errores de autenticación en login y signup
- eliminadas carpetas de saga
- limpieza de código con linter

QA:
- se debería mostrar vista de login al abrir la app
- al ingresar un usuario o contraseña inválida debería arrojar un error en rojo
- al apretar "no tienes cuenta" se debría cambiar a vista de registro y viceversa
- al registrarse debería mostrar usuario y token en pantalla en blanco si credenciales son válidas (error en rojo en caso contrario)
- Habiendo podido registrarse debería poder logearse con el mismo usuario si se reinicia la app

info adicional:
- crear .env.development en carpeta raíz y agregar "HOST=https://pl-super-kitchen-staging.herokuapp.com/" para que funcione la api

2021-05-04 19:34 UTC, agomezcampero requested changes
Se ve bastante bien, deje un par de comentarios chicos. Creo que lo más importante es sacar la lógica de llamadas a la API del store (que la store solamente haga `somethingApi.method().then(...).catch(...)`)

2021-05-04 19:34 UTC, agomezcampero commented on screens/LogInScreen.js
> +  }, [loginError]);
se podría hacer esto directamente en el componente y no usar el useEffect

2021-05-04 19:34 UTC, agomezcampero commented on screens/LogInScreen.js
> +        </Text>
```suggestion
{ loginError &&
        <Text style={styles.errorMessage}>
          Inténtalo de nuevo: email o contraseña inválido
        </Text>
        }
```

2021-05-04 19:34 UTC, agomezcampero commented on screens/LogInScreen.js
> +          <Text style={{ textAlign: 'center', color: '#074eec', marginTop: '4%' }}>
sería bueno guardar los colores en alguna carpeta para poder modificarlos todos de una después

2021-05-04 19:34 UTC, agomezcampero commented on store/store.js
> +  }),
sería bueno mover está lógica a un archivo `api/sessions.js` que hace un` default export` que después importamos como `seesionsApi`

me imagino que los `thunks` quedarían algo así:
```suggestion
login: thunk(async (actions, payload) => {
  sessionsApi.login(payload)
    .then(res => {
        actions.setUserAndApiHeaders(res)
    }).catch((error) => {
        actions.setLoginError(error.response.data.message);
    });
  }),
  signUp: thunk(async (actions, payload) => {
  sessionsApi.signUp(payload)
    .then(res => {
        actions.setUserAndApiHeaders(res)
    }).catch((error) => {
        actions.setSignUpError(error.response.data.message);
    });
  }),
```

2021-05-04 19:35 UTC, agomezcampero commented on screens/LogInScreen.js
> +  }, [loginError]);
voy a cerrar este, de esta forma queda igual al `signup`

2021-05-05 12:31 UTC, agomezcampero commented on api/sessions.js
> +  login: async (payload) => {
no es necesario poner async si no vas a usar await

2021-05-05 12:31 UTC, agomezcampero commented on api/sessions.js
> +  signUp: async (payload) => {
lo mismo acá

2021-05-05 12:33 UTC, agomezcampero approved these changes
Lo veo bien, saquen esos async y mergean :)

2021-05-05 13:40 UTC, jmsilvas commented on api/sessions.js
> +  login: async (payload) => {
Pefecto! Pensé preguntarlo de hecho jajaj

2021-05-05 15:36 UTC, fthurtado approved these changes
Se ve todo bien, go con el mere 🚀

2021-05-05 15:38 UTC, merged