Pending fixes
platanus/2021-1-Grupo4-Movil pull request #46
Opened 2021-06-28 17:45 UTC by jmsilvas

## Que se hizo
- agregar ojo para poder visualizar clave ingresada en input tanto en login como en signup
- cambiar fondo de index de recetas a blanco como estaban los demás
- Permitir editar todos los campos de ingrediente proveniente del scrapper, excepto su proveedor.

## QA 
- en inicio de sesión ingresar una clave y al pulsar el icono del ojo deberia verse que se escribio y ocultarse en caso de volverse a apretar. Probar los mismo en vista de registro.
- Para probar que se puede editar ingrediente del scrapper, buscar y agregar uno y al visualizarse el form editar todos los campos que se pueden editar. El proveedor debiese aoarecer en gris dado que ese campo no es editable en este caso

2021-06-28 23:10 UTC, fthurtado requested changes
Dejé un par de sugerencias de identación.

Probando me di cuenta de un error para que lo veas. Cuando uno pasa de la contraseña abierta a cerrada se reinicio el input

<img width="264" alt="Screen Shot 2021-06-28 at 19 08 45" src="https://user-images.githubusercontent.com/48318555/123714427-44e27680-d844-11eb-9b9b-8aa4de0c17e8.png">

Por ejemplo, si cierro el ojo en ese caso y escribo un carácter más se va a reiniciar. Como se muestra en la siguiente foto.

<img width="252" alt="Screen Shot 2021-06-28 at 19 09 21" src="https://user-images.githubusercontent.com/48318555/123714467-5a57a080-d844-11eb-8aaa-6e71bb86c010.png">

2021-06-28 23:10 UTC, fthurtado commented on screens/Ingredients/FormIngredientScreen.js
> +              </Text>
```suggestion
              <Text style={styles.inputLabel}>
                Proveedor
              </Text>
```

2021-06-28 23:10 UTC, fthurtado commented on screens/Ingredients/FormIngredientScreen.js
> +              </Text>
```suggestion
              <Text style={styles.inputLabel}>
                Proveedor
              </Text>
```

2021-06-28 23:10 UTC, fthurtado commented on screens/SignUpScreen.js
>          <Text style={styles.loginText}> Confirmar Contraseña:</Text>
```suggestion
        <Text style={styles.loginText}>
          Confirmar Contraseña:
        </Text>
```

2021-06-29 03:32 UTC, jmsilvas commented
> Dejé un par de sugerencias de identación.
> 
> Probando me di cuenta de un error para que lo veas. Cuando uno pasa de la contraseña abierta a cerrada se reinicio el input
> 
> <img alt="Screen Shot 2021-06-28 at 19 08 45" width="264" src="https://user-images.githubusercontent.com/48318555/123714427-44e27680-d844-11eb-9b9b-8aa4de0c17e8.png">
> 
> Por ejemplo, si cierro el ojo en ese caso y escribo un carácter más se va a reiniciar. Como se muestra en la siguiente foto.
> 
> <img alt="Screen Shot 2021-06-28 at 19 09 21" width="252" src="https://user-images.githubusercontent.com/48318555/123714467-5a57a080-d844-11eb-8aaa-6e71bb86c010.png">

Averigüe y por defecto en IOS te resetea el texto cuando pones secureTextEntry={true}. Al parecer no se puede hacer mucho. Pero en Android no pasa! Aquí lo que vi (el link al que redirige esta publicación): https://stackoverflow.com/questions/48873737/when-i-use-securetextentry-true-the-input-reset-the-value-when-try-to-type-a

2021-06-29 13:12 UTC, fthurtado commented
> > Dejé un par de sugerencias de identación.
> > Probando me di cuenta de un error para que lo veas. Cuando uno pasa de la contraseña abierta a cerrada se reinicio el input
> > <img alt="Screen Shot 2021-06-28 at 19 08 45" width="264" src="https://user-images.githubusercontent.com/48318555/123714427-44e27680-d844-11eb-9b9b-8aa4de0c17e8.png">
> > Por ejemplo, si cierro el ojo en ese caso y escribo un carácter más se va a reiniciar. Como se muestra en la siguiente foto.
> > <img alt="Screen Shot 2021-06-28 at 19 09 21" width="252" src="https://user-images.githubusercontent.com/48318555/123714467-5a57a080-d844-11eb-8aaa-6e71bb86c010.png">
> 
> Averigüe y por defecto en IOS te resetea el texto cuando pones secureTextEntry={true}. Al parecer no se puede hacer mucho. Pero en Android no pasa! Aquí lo que vi (el link al que redirige esta publicación): https://stackoverflow.com/questions/48873737/when-i-use-securetextentry-true-the-input-reset-the-value-when-try-to-type-a

Wired! No sé si @AndresGarciadelaHuerta sabe algo sobre esto!!

Lo demás se ve todo 👌

2021-06-29 13:12 UTC, fthurtado approved these changes

2021-06-29 13:33 UTC, AndresGarciadelaHuerta reviewed
Lo veo bien, dejo un cambio chico nomás sobre el nombre de una variable de estado.

2021-06-29 13:33 UTC, AndresGarciadelaHuerta commented on screens/SignUpScreen.js
> +  const [hidePassword2, setHidePassword2] = useState(true);
trataría de poner nombres descriptivos/legibles como `hideFirstPassword` y `hideSecondPassword`

2021-06-29 13:57 UTC, AndresGarciadelaHuerta approved these changes

2021-06-29 14:04 UTC, merged